### PR TITLE
add PrevPageNum and NextPageNum to PaginatedList

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by dizzystuff** [comment]
@xini would you mind adjusting this so that they're returning null if they're not otherwise returning an int? 

So that in effect we get a reliable ?int return type (though not adding an explicit return type for now to maintain backwards compat).

**Comment by xini** [comment]
@dizzystuff sure. done.

**Comment by dizzystuff** [comment]
@xini done, thanks! tagged 1.3.0.

**Comment by xini** [comment]
thank you!

**Pull request merged**
